import type { Metadata } from "next";
import { Noto_Sans_TC } from "next/font/google"; 
import "./globals.css"; 
import DynamicManifest from "@/components/DynamicManifest"; // 1. 引入剛剛做的組件

const notoSansTC = Noto_Sans_TC({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  preload: false,
});

export const metadata: Metadata = {
  title: "326點餐",
  description: "Generated by create next app",
  // ⚠️ 注意：這裡原本的 manifest 設定要刪掉，交給下面的組件處理
  // manifest: "/manifest.json", 
  themeColor: "#000000",
  viewport: {
    width: "device-width",
    initialScale: 1,
    maximumScale: 1, 
    userScalable: false,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh-TW">
      <head>
        {/* 2. 把動態 Manifest 組件放在這裡 */}
        <DynamicManifest />
      </head>
      <body className={notoSansTC.className}>
        {children}
      </body>
    </html>
  );
}