import type { Metadata } from "next";
import { Noto_Sans_TC } from "next/font/google"; // 記得引入字體
import "./globals.css"; // 記得引入全域樣式

// 設定字體
const notoSansTC = Noto_Sans_TC({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  preload: false,
});

// 這是你剛剛寫的 metadata
export const metadata: Metadata = {
  title: "326點餐",
  description: "Generated by create next app",
  manifest: "/manifest.json", 
  // themeColor 與 viewport 在新版 Next.js 建議分開寫，但在這裡寫通常也會警告而已，不影響運作
  // 若要標準寫法，viewport 應該獨立匯出，但我們先求能動就好
};

// 🌟 這就是你原本少的那一段！
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh-TW">
      <body className={notoSansTC.className}>
        {children}
      </body>
    </html>
  );
}