import type { Metadata, Viewport } from "next"; // 1. 多引入 Viewport 型別
import { Noto_Sans_TC } from "next/font/google"; 
import "./globals.css"; 
import DynamicManifest from "@/components/DynamicManifest"; 

const notoSansTC = Noto_Sans_TC({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  preload: false,
});

// 2. 這是 SEO 相關設定 (這裡只留標題跟敘述，移除 viewport 相關設定)
export const metadata: Metadata = {
  title: "326點餐",
  description: "Generated by create next app",
};

// 3. 🆕 新增這個：這是視窗與顏色設定 (必須獨立出來寫)
export const viewport: Viewport = {
  themeColor: "#000000",
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh-TW">
      <head>
        {/* 把動態 Manifest 組件放在這裡 */}
        <DynamicManifest />
      </head>
      <body className={notoSansTC.className}>
        {children}
      </body>
    </html>
  );
}